### ISSUE TITLE
Issue when loading svg

### ISSUE THREAD

**Issue by BennieBe** [monoguerin/vue-svg-sprite-loader#1]
When I try to add my component, I get this error message:
[Vue warn]: Invalid Component definition: /fonts/map.svg?3fefec458080b53ef55ec2540aef175d found in ---> <SvgMap> at resources/assets/js/components/landingPage/components/ProviderMap.vue <LandingPage> at resources/assets/js/components/landingPage/landingPage.vue <Root>

Why is that happening? What do I need to do to load this svg as a component correctly?

My component:

```
<template>
  <div id="svgMap">
    <svg-provider-map></svg-provider-map>
  </div>
</template>

<script>
import SvgProviderMap from '../../../../svg/ProviderMap.svg';

export default {
  name: 'svgMap',
  components: {
    'svg-provider-map': SvgProviderMap
  }
};
</script>
<style>
</style>
```

My webpack config:
```
mix.webpackConfig({
  module: {
    rules: [
      {
        test: /\.svg$/,
        loader: 'vue-svg-sprite-loader'
      }
    ]
  }
});
```

I am using laravel mix to load this plugin in webpack.

**Comment by monoguerin** [comment]
Is the svg that you are trying to use a sprite SVG or just a single SVG?, if it is just a single and you don't have to handle a sprite SVG please use https://www.npmjs.com/package/vue-svg-loader

**Comment by BennieBe** [comment]
I tried to use vue-svg-loader package, it gives me the same error, could it be that something is wrong with the svg file I am using? Is there any prerequisites towards how such a file must look like?

**Comment by monoguerin** [comment]
not really it is just any SVG file should work,  but seems to be more related to the way you are modifying the webpack config instead, seems that the webpack loader is not correctly added

**Comment by BennieBe** [comment]
Well, I am using laravel, I do not access the config of webpack directly, but load it using laravel.mix : 
https://github.com/JeffreyWay/laravel-mix/blob/master/docs/quick-webpack-configuration.md
Could that be the issue? Am I doing it wrong using it this way here?

```
mix.webpackConfig({
  module: {
    rules: [
      {
        test: /\.svg$/,
        loader: 'vue-svg-sprite-loader'
      }
    ]
  }
});
```

**Comment by monoguerin** [comment]
To be honest I am not sure, can you test with another loader or overwriting another rule of the webpack config first?

**Comment by BennieBe** [comment]
Well, in the end, I switched back to standard svg loading and importing the svg into my component manually, I will close this issue, thanks for your help!
