### ISSUE TITLE
Invalid Component definition warning

### ISSUE THREAD

**Issue by igorkurochka** [monoguerin/vue-svg-sprite-loader#9]
tried your package to load an svg sprite icon, icon didn't render and in devtools console got this message:

> [Vue warn]: Invalid Component definition: data:image/svg+xml;base64,bW9kdWxlLmV4cG9ydHMgPSB7cmVuZGVyOmZ1bmN0aW9uIGFub255bW91cygKKSB7CndpdGgodGhpcyl7cmV0dXJuIF9jKCdzdmcnLHthdHRyczp7InhtbG5zIjoiaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciLCJhcmlhLWxhYmVsbGVkYnkiOiJhcnJvdy1ib3R0b20taWNvbiIsInZpZXdCb3giOiIwIDAgMTAgNSJ9fSxbX2MoJ3RpdGxlJyxbX3YoImFycm93LWJvdHRvbS1pY29uIildKSxfYygncGF0aCcse2F0dHJzOnsiZCI6Ik0wIDBsNSA1IDUtNXoifX0pXSl9Cn19Ow==

**Comment by vinaygunnam** [comment]
Here is a sample working repo to that shows the usage of svg sprites using vue-svg-sprite-loader.
https://github.com/vinaygunnam/vue-sprite-sample

Could you fork this to reproduce the issue you are seeing?
